# Generated by Django 4.1.3 on 2022-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
            ],
        ),
        migrations.CreateModel(
            name='ModifyDpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdpi', models.CharField(max_length=20, unique=True, verbose_name='현재 감도')),
            ],
        ),
    ]
